import { QuestionInfo } from '../types';

// 설문 질문 정보
export const SURVEY_QUESTIONS: QuestionInfo[] = [
  {
    number: 1,
    title: '흡연을 하시나요?',
    type: 'radio',
    name: 'smoking',
    options: [
      { value: 'yes', label: '예', id: 'smoking_yes' },
      { value: 'quit', label: '금연중', id: 'smoking_quit' },
      { value: 'no', label: '아니오', id: 'smoking_no' },
    ],
  },
  {
    number: 2,
    title: '가족력이 있는 질병이 있나요?',
    subtitle: '없음 선택 또는 질병 중복 체크 가능',
    type: 'checkbox',
    name: 'familyHistory',
    options: [
      { value: 'none', label: '없음', id: 'family_none' },
      { value: 'hypertension', label: '고혈압', id: 'family_hypertension' },
      { value: 'stroke', label: '뇌혈관질환', id: 'family_stroke' },
      { value: 'diabetes', label: '당뇨', id: 'family_diabetes' },
      { value: 'colon_cancer', label: '대장암', id: 'family_colon_cancer' },
      { value: 'heart_disease', label: '심혈관질환', id: 'family_heart_disease' },
      { value: 'thyroid_cancer', label: '갑상선암', id: 'family_thyroid_cancer' },
      { value: 'kidney_cancer', label: '신장암', id: 'family_kidney_cancer' },
      { value: 'breast_cancer', label: '유방암', id: 'family_breast_cancer' },
      { value: 'prostate_cancer', label: '전립선암', id: 'family_prostate_cancer' },
      { value: 'lung_cancer', label: '폐암', id: 'family_lung_cancer' },
    ],
  },
  {
    number: 3,
    title: '현재 앓고 있는 질환이 있나요?',
    subtitle: '없음 선택 또는 질병 중복 체크 가능',
    type: 'checkbox',
    name: 'currentDisease',
    options: [
      { value: 'none', label: '없음', id: 'current_none' },
      { value: 'cirrhosis', label: '간경화', id: 'current_cirrhosis' },
      { value: 'thyroiditis', label: '갑상선염', id: 'current_thyroiditis' },
      { value: 'hypertension', label: '고혈압', id: 'current_hypertension' },
      { value: 'colitis', label: '궤양성대장염', id: 'current_colitis' },
      { value: 'stroke', label: '뇌혈관질환', id: 'current_stroke' },
      { value: 'late_menopause', label: '늦은 폐경', id: 'current_late_menopause' },
      { value: 'gallbladder_polyp', label: '담낭용종', id: 'current_gallbladder_polyp' },
      { value: 'gallstones', label: '담석증', id: 'current_gallstones' },
      { value: 'diabetes', label: '당뇨', id: 'current_diabetes' },
      { value: 'gastritis', label: '만성위염', id: 'current_gastritis' },
      { value: 'hepatitis_b', label: '바이러스성 간염 B형', id: 'current_hepatitis_b' },
      { value: 'hepatitis_c', label: '바이러스성 간염 C형', id: 'current_hepatitis_c' },
      { value: 'heart_disease', label: '심혈관질환', id: 'current_heart_disease' },
      { value: 'alzheimer', label: '알츠하이머병', id: 'current_alzheimer' },
      { value: 'typhoid_carrier', label: '장티푸스 보균자', id: 'current_typhoid_carrier' },
      { value: 'pancreatitis', label: '췌장염', id: 'current_pancreatitis' },
      { value: 'helicobacter', label: '헬리코박터균 감염', id: 'current_helicobacter' },
    ],
  },
  {
    number: 4,
    title: '현재 앓고 있는 암이 있나요?',
    subtitle: '없음 선택 또는 암 중복 체크 가능',
    type: 'checkbox',
    name: 'currentCancer',
    options: [
      { value: 'none', label: '없음', id: 'cancer_none' },
      { value: 'liver', label: '간암', id: 'cancer_liver' },
      { value: 'thyroid', label: '갑상선암', id: 'cancer_thyroid' },
      { value: 'gallbladder', label: '담낭암', id: 'cancer_gallbladder' },
      { value: 'colon', label: '대장암', id: 'cancer_colon' },
      { value: 'kidney', label: '신장암', id: 'cancer_kidney' },
      { value: 'stomach', label: '위암', id: 'cancer_stomach' },
      { value: 'breast', label: '유방암', id: 'cancer_breast' },
      { value: 'prostate', label: '전립선암', id: 'cancer_prostate' },
      { value: 'pancreatic', label: '췌장암', id: 'cancer_pancreatic' },
      { value: 'lung', label: '폐암', id: 'cancer_lung' },
    ],
  },
  {
    number: 5,
    title: '음주를 하시나요?',
    subtitle: '기준: 주 1회 이상, 소주 1병 이상 또는 맥주 1000cc 이상',
    type: 'radio',
    name: 'drinking',
    options: [
      { value: 'yes', label: '예', id: 'drinking_yes' },
      { value: 'no', label: '아니오', id: 'drinking_no' },
    ],
  },
];

